name: catchAPI
author: 和平peaceful
version: '1.0.5'
main: top.peacefuly.catchapi.CatchAPI
api-version: '1.20'
description: 抓取API数据
website: www.49team.org
load: POSTWORLD
libraries:
  - org.jetbrains:annotations:13.0